#!/usr/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later

if [[ ! -f .savesave.example ]]; then
	>&2 echo not in source tree
	exit 1
fi

src=$(echo platfree/*.c platspec/**/*.c)
dest=include/constructor.h

entry=$(awk '
/^$/ {
	buf = ""
	next
}

/^CONSTRUCTOR\(/ {

	split($0, res, /[()]/)
	name = res[2]

	print $0 "†" buf "†" name

	nextfile
}

{
	buf = $0
}' $src)

cat <<EOF > $dest
/* SPDX-License-Identifier: GPL-3.0-or-later */
/*
 * Copyright 2024 Jiamu Sun <barroit@linux.com>
 *
 * Generated by scripts/gen-constructor.sh
 */

#ifndef BRTGEN_CONSTRUCTOR_H
#define BRTGEN_CONSTRUCTOR_H

#define USESTDIO

#if defined(__unix__)
# define __CONSTRUCTOR CONSTRUCTOR
# define CONSTRUCTOR(name) static void __attribute__((constructor)) name(void)
#elif defined(_WIN32)
/*
 * __attribute__((constructor)) doesn't work on windows, we need to call these
 * functions manually
 */
# define CONSTRUCTOR(name) void name(void)

EOF

awk -F'†' '{ print $1 ";" }' <<< $entry >> $dest

cat <<EOF >> $dest

#define CONSTRUCTOR_LIST_INIT { \\
EOF

awk -F'†' '!/USESTDIO/ { print "\t" $NF ", \\" }' <<< $entry >> $dest

cat <<EOF >> $dest
}

#define CONSTRUCTOR_LIST_INIT_USESTDIO { \\
EOF

awk -F'†' '/USESTDIO/ { print "\t" $NF ", \\" }' <<< $entry >> $dest

cat <<EOF >> $dest
}

EOF

awk -F'†' '
{
	print "typedef typeof(&" $3 ") constructor_t;"
	exit
}' <<< $entry >> $dest

cat <<EOF >> $dest
#endif

#endif /* BRTGEN_CONSTRUCTOR_H */
EOF
