#!/usr/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

if [[ ! -f .savesave.example ]]; then
	>&2 echo not in source tree
	exit 1
fi

src=$(echo platfree/command/*.c)
dest=include/command.h

declare=$(grep -Eh '^(LONGRUNNING[[:space:]]+)?int cmd_*' $src)

cat <<EOF > $dest
/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * Copyright 2024 Jiamu Sun
 *
 * Contact: barroit@linux.com
 *
 * Generated by scripts/gencmdh.sh
 * This file should only be included in arugpar.h.
 */

#ifndef GEN_COMMAND_H
#define GEN_COMMAND_H

#ifdef __cplusplus
extern "C" {
#endif

EOF

awk '{ print $0";" }' <<< $declare >> $dest

cat <<EOF >> $dest

#define APOPT_MAIN_COMMAND_INIT(v) { \\
EOF

name=$(awk -F '[_()]' '{ print $2 }' <<< $declare)
awk '{ print "\tAPOPT_SUBCOMMAND(\""$0"\", (v), cmd_"$0"), \\" }' \
    <<< $name >> $dest

cat <<EOF >> $dest
	APOPT_END(), \\
}

#define APOPT_LONGRUNNING_INIT { \\
EOF

longrun=$(grep -E '^LONGRUNNING' <<< $declare)
name=$(awk -F '[_()]' '{ print $2 }' <<< $longrun)

printf '\t"%s", \\\n' $name >> $dest

cat <<EOF >> $dest
}

#ifdef __cplusplus
}
#endif

#endif /* GEN_COMMAND_H */
EOF
