#!/usr/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

if [[ ! -f .savesave.example ]]; then
	>&2 echo not in source tree
	exit 1
fi

src=$(echo platfree/command/*.c)
dest=include/command.h

commands=$(grep -h '^int cmd_*' $src | awk -F '[_()]' '{ print $2 }')

cat <<EOF > $dest
/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * Copyright 2024 Jiamu Sun
 *
 * Contact: barroit@linux.com
 *
 * Generated by scripts/gencmdh.sh
 * This file should only be included in arugpar.h.
 */

#ifndef GEN_COMMAND_H
#define GEN_COMMAND_H

#ifdef __cplusplus
extern "C" {
#endif

EOF

printf 'int cmd_%s(int argc, const char **argv);\n' $commands >> $dest

cat <<EOF >> $dest

#define APOPT_MAIN_COMMAND_INIT(v) { \\
EOF

for cmd in $commands; do
	printf '\tAPOPT_SUBCOMMAND("%s", (v), cmd_%s), \\\n' $cmd $cmd
done >> $dest

cat <<EOF >> $dest
	APOPT_END(), \\
}

#ifdef __cplusplus
}
#endif

#endif /* GEN_COMMAND_H */
EOF
