#!/usr/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

if [[ ! -f .savesave.example ]]; then
	>&2 echo not in source tree
	exit 1
fi

src=$(echo sscmds/*.c)
dest=include/command.h

declare=$(awk '
/^$/ {
	buf = ""
	next
}

/^int cmd_[a-zA-Z_]+\(/ {
	getline mas
	if (!mas)
		exit 1

	if (buf)
		print $0 " " mas " " buf
	else
		print $0 " " mas

	nextfile
}

{
	if (buf)
		buf = buf " | "
	buf = buf "CMD_" $0
}' $src)

cat <<EOF > $dest
/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * Copyright 2024 Jiamu Sun
 *
 * Contact: barroit@linux.com
 *
 * Generated by scripts/genh-command.sh
 */

#ifndef GENH_COMMAND_H
#define GENH_COMMAND_H

#define UNIQUEPROC  /* can only be one process at a time */
#define USEDOTSAV   /* use dotsav */
#define LONGRUNNING /* long-running command */

#define CMD_UNIQUEPROC  (1 << 0)
#define CMD_USEDOTSAV   (1 << 1)
#define CMD_LONGRUNNING (1 << 2)

#define CMDDESCRIP(mas)

EOF

awk -F')' '{ print $1 ");" }' <<< $declare >> $dest

cat <<EOF >> $dest

#define APOPT_MAINCOMMAND(v) \\
EOF

awk -F'[()]' '
{
	cmd = substr($1, 5)
	printf "\tAPOPT_SUBCOMMAND(\"%s\", (v), N_(%s), %s, ", \
	       substr(cmd, 5), $4, cmd

	if ($5)
		printf "%s)", substr($5, 2)
	else
		printf "0)"

	if (NR != n)
		print ", \\"
	else
		print ""

}' n=$(wc -l <<< $declare) <<< $declare  >> $dest

cat <<EOF >> $dest

#endif /* GENH_COMMAND_H */
EOF
