#!/usr/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

if [[ ! -f .savesave.example ]]; then
	>&2 echo not in source tree
	exit 1
fi

src=$(echo platfree/*.c uni/*.c win/*.c)
dest=include/constructor.h

declare=$(grep -Eh '^(USESTDIO[[:space:]]+)?CONSTRUCTOR\(*' $src | sort | uniq)

cat <<EOF > $dest
/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * Copyright 2024 Jiamu Sun
 *
 * Contact: barroit@linux.com
 *
 * Generated by scripts/genh-constructor.sh
 */

#ifndef _WIN32
# error "constructor.h is win-spec"
#endif

#ifndef GENH_CONSTRUCTOR_H
#define GENH_CONSTRUCTOR_H

EOF

awk '{ print $0";" }' <<< $declare >> $dest

cat <<EOF >> $dest

#define CONSTRUCTOR_LIST_INIT { \\
EOF

ret=$(grep -v '^USESTDIO' <<< $declare)
name=$(awk -F '[()]' '{ print $2 }' <<< $ret)
printf '\t%s, \\\n' $name >> $dest

cat <<EOF >> $dest
}

#define CONSTRUCTOR_USESTDIO_LIST_INIT { \\
EOF

ret=$(grep '^USESTDIO' <<< $declare)
name=$(awk -F '[()]' '{ print $2 }' <<< $ret)
printf '\t%s, \\\n' $name >> $dest

cat <<EOF >> $dest
}

EOF

echo "typedef typeof(&$(head -n 1  <<< $name)) constructor_t;" >> $dest

cat <<EOF >> $dest

#endif /* GENH_CONSTRUCTOR_H */
EOF
