#!/usr/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

if [[ ! -f .savesave.example ]]; then
	>&2 echo not in source tree
	exit 1
fi

src=$(echo platfree/command/*.c)
dest=include/command.h

declare=$(awk '
/^$/ {
	buf = ""
	next
}

/^int cmd_[a-zA-Z_]+\(/ {
	if (buf != "")
		print $0 " " buf
	else
		print $0
}

{
	if (buf != "")
		buf = buf " | "
	buf = buf "CMD_" $0
}' $src)

cat <<EOF > $dest
/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * Copyright 2024 Jiamu Sun
 *
 * Contact: barroit@linux.com
 *
 * Generated by scripts/genh-command.sh
 */

#ifndef GENH_COMMAND_H
#define GENH_COMMAND_H

#define UNIQUEPROC  /* can only be one process at a time */
#define USEDOTSAV   /* use dotsav */
#define LONGRUNNING /* long-running command */

#define CMD_UNIQUEPROC  (1 << 0)
#define CMD_USEDOTSAV   (1 << 1)
#define CMD_LONGRUNNING (1 << 2)

EOF

awk -F')' '{ print $1 ");" }' <<< $declare >> $dest

cat <<EOF >> $dest

#define MAINCOMMAND_LIST_INIT(v) { \\
EOF

awk -F'[()]' '
{
	cmd = substr($1, 5)
	printf "\tAPOPT_SUBCOMMAND(\"%s\", (v), %s, ", substr(cmd, 5), cmd
	if ($3)
		printf "%s), \\\n", substr($3, 2)
	else
		print "0), \\"
}' <<< $declare >> $dest

cat <<EOF >> $dest
	APOPT_END(), \\
}

#endif /* GENH_COMMAND_H */
EOF
