#!/usr/bin/bash
# SPDX-License-Identifier: GPL-3.0

die()
{
	>&2 echo "fatal: $*"
	exit 1
}

arr_find_elem()
{
	for word in ${@:2}; do
		if [[ "$1" = $word ]]; then
			return 0
		fi
	done
	return 1
}

if [[ ! -f Kconfig ]]; then
	die 'not in project root directory'
fi

ignores=(COPYING orange.ico)

while read; do
	if [[ "$REPLY" =~ .*[[:space:]].* ]]; then
		die "path ‘$REPLY’ contains space"
	fi

	if arr_find_elem $REPLY ${ignores[@]}; then
		continue;
	fi

	grep -nH "[[:space:]]$" "$REPLY" | awk -F':' '{print $1 ":" $2}'
done < <(git ls-files)
