/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * Copyright 2024 Jiamu Sun
 *
 * Contact: barroit@linux.com
 *
 * Generated by scripts/genh-command.sh
 */

#ifndef GENH_COMMAND_H
#define GENH_COMMAND_H

#define LONGRUNNING
#define USEDOTSAV

#define CMD_LONGRUNNING (1 << 0)
#define CMD_USEDOTSAV   (1 << 1)

int cmd_help(int argc, const char **argv);
int cmd_sizeof(int argc, const char **argv);
int cmd_start(int argc, const char **argv);
int cmd_version(int argc, const char **argv);

#define MAINCOMMAND_LIST_INIT(v) { \
	APOPT_SUBCOMMAND("help", (v), cmd_help, 0), \
	APOPT_SUBCOMMAND("sizeof", (v), cmd_sizeof, CMD_USEDOTSAV), \
	APOPT_SUBCOMMAND("start", (v), cmd_start, CMD_LONGRUNNING | CMD_USEDOTSAV), \
	APOPT_SUBCOMMAND("version", (v), cmd_version, 0), \
	APOPT_END(), \
}

#endif /* GENH_COMMAND_H */
