/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * Copyright 2024 Jiamu Sun
 *
 * Contact: barroit@linux.com
 *
 * Generated by scripts/genh-command.sh
 * This file should only be included in arugpar.h.
 */

#ifndef GENH_COMMAND_H
#define GENH_COMMAND_H

int cmd_help(int argc, const char **argv);
int cmd_sizeof(int argc, const char **argv);
LONGRUNNING int cmd_start(int argc, const char **argv);
int cmd_version(int argc, const char **argv);

#define MAINCOMMAND_LIST_INIT(v) { \
	APOPT_SUBCOMMAND("help", (v), cmd_help), \
	APOPT_SUBCOMMAND("sizeof", (v), cmd_sizeof), \
	APOPT_SUBCOMMAND("start", (v), cmd_start), \
	APOPT_SUBCOMMAND("version", (v), cmd_version), \
	APOPT_END(), \
}

#define LONGRUNNING_LIST_INIT { \
	"start", \
}

#endif /* GENH_COMMAND_H */
