/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * Copyright 2024 Jiamu Sun
 *
 * Contact: barroit@linux.com
 *
 * Generated by scripts/genh-constructor.sh
 */

#ifndef _WIN32
# error "constructor.h is win-spec"
#endif

#ifndef GENH_CONSTRUCTOR_H
#define GENH_CONSTRUCTOR_H

CONSTRUCTOR(init_u8tstr_table);
CONSTRUCTOR(setup_crt_report_hook);
CONSTRUCTOR(setup_executable_dirname);
USESTDIO CONSTRUCTOR(check_libzstd_compat);
USESTDIO CONSTRUCTOR(check_os_version);
USESTDIO CONSTRUCTOR(setup_console_codepage);

#define CONSTRUCTOR_LIST_INIT { \
	init_u8tstr_table, \
	setup_crt_report_hook, \
	setup_executable_dirname, \
}

#define CONSTRUCTOR_USESTDIO_LIST_INIT { \
	check_libzstd_compat, \
	check_os_version, \
	setup_console_codepage, \
}

typedef typeof(&check_libzstd_compat) constructor_t;

#endif /* GENH_CONSTRUCTOR_H */
